# Generated by Django 4.0.1 on 2022-01-29 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('phonenumber', models.CharField(max_length=200, null=True, verbose_name='联系电话')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=200, null=True, verbose_name='产品编号')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('spec', models.CharField(max_length=200, verbose_name='尺寸规格')),
                ('image', models.CharField(max_length=200, null=True, verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('customer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='common.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=200, verbose_name='订单编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('num', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('customer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='common.customer')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='common.product')),
            ],
        ),
    ]
