# Generated by Django 4.0.1 on 2022-02-08 14:07

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.models.directory_path, verbose_name='照片'),
        ),
    ]
