# Generated by Django 4.0.1 on 2022-02-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_product_image_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
